### ISSUE TITLE
Use cast in memory allocations

### ISSUE THREAD

**Issue by Speedstack79** [PenguinGovernor/ccrypt#1]
Although this program is written in C, if this were compiled in C++, it would not work. I believe it is best for this program to be compatible with both C and C++.
malloc returns a void * pointer and is automatically casted to the appropriate type in C, but not in C++ therefore you have to manually cast it.
example:
`  efile_t* efile = malloc(sizeof(efile_t));`
to
`  efile_t* efile = (efile_t *) malloc(sizeof(efile_t));`

**Comment by PenguinGovernor** [comment]
Fixed in the latest commit! Thanks for the heads up!
e778d5b5210a30465a8b74ae42bb072c021ad63a
